const constants = {
 ADD_TO_CART: "ADD_TO_CART",
 REMOVE_FROM_CART: "REMOVE_FROM_CART",
 SIZE_CHANGE: "SIZE_CHANGE",
 GEM_STONE_QUALITY_UPDATE: "GEM_STONE_QUALITY_UPDATE",
 CARAT_WEIGHT_UPDATE: "CARAT_WEIGHT_UPDATE",
 METAL_TYPE_UPDATE: "METAL_TYPE_UPDATE",
 PRICE_UPDATE: "PRICE_UPDATE",
}

export default constants;